<?xml version='1.0' encoding='UTF-8'?>
<Library LVVersion="14008000">
	<Property Name="NI.Lib.Icon" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!(]!!!*Q(C=\&gt;8"=&gt;MQ%!8143;(8.6"2CVM#WJ",7Q,SN&amp;(N&lt;!NK!7VM#WI"&lt;8A0$%94UZ2$P%E"Y.?G@I%A7=11U&gt;M\7P%FXB^VL\`NHV=@X&lt;^39O0^N(_&lt;8NZOEH@@=^_CM?,3)VK63LD-&gt;8LS%=_]J'0@/1N&lt;XH,7^\SFJ?]Z#5P?=F,HP+5JTTF+5`Z&gt;MB$(P+1)YX*RU2DU$(![)Q3YW.YBG&gt;YBM@8'*\B':\B'2Z&gt;9HC':XC':XD=&amp;M-T0--T0-.DK%USWS(H'2\$2`-U4`-U4`/9-JKH!&gt;JE&lt;?!W#%;UC_WE?:KH?:R']T20]T20]\A=T&gt;-]T&gt;-]T?/7&lt;66[UTQ//9^BIHC+JXC+JXA-(=640-640-6DOCC?YCG)-G%:(#(+4;6$_6)]R?.8&amp;%`R&amp;%`R&amp;)^,WR/K&lt;75?GM=BZUG?Z%G?Z%E?1U4S*%`S*%`S'$;3*XG3*XG3RV320-G40!G3*D6^J-(3D;F4#J,(T\:&lt;=HN+P5FS/S,7ZIWV+7.NNFC&lt;+.&lt;GC0819TX-7!]JVO,(7N29CR6L%7,^=&lt;(1M4#R*IFV][.DX(X?V&amp;6&gt;V&amp;G&gt;V&amp;%&gt;V&amp;\N(L@_Z9\X_TVONVN=L^?Y8#ZR0J`D&gt;$L&amp;]8C-Q_%1_`U_&gt;LP&gt;WWPAG_0NB@$TP@4C`%`KH@[8`A@PRPA=PYZLD8Y!#/7SO!!!!!!</Property>
	<Property Name="NI.Lib.SourceVersion" Type="Int">335577088</Property>
	<Property Name="NI.Lib.Version" Type="Str">1.0.0.0</Property>
	<Item Name="A安全门禁用" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\A安全门禁用</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\A安全门禁用</Property>
	</Item>
	<Item Name="A复位" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\A复位</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\A复位</Property>
	</Item>
	<Item Name="A工位NG样件需求" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\A工位NG样件需求</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\A工位NG样件需求</Property>
	</Item>
	<Item Name="A工位OK样件需求" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\A工位OK样件需求</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\A工位OK样件需求</Property>
	</Item>
	<Item Name="A工位校准时间到" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\A工位校准时间到</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\A工位校准时间到</Property>
	</Item>
	<Item Name="A启动信号" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\A启动信号</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\A启动信号</Property>
	</Item>
	<Item Name="A切换为手动" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\A切换为手动</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\A切换为手动</Property>
	</Item>
	<Item Name="A扫码OK" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\A扫码OK</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\A扫码OK</Property>
	</Item>
	<Item Name="A手动封堵" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\A手动封堵</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\A手动封堵</Property>
	</Item>
	<Item Name="A手动盖章" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\A手动盖章</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\A手动盖章</Property>
	</Item>
	<Item Name="A手动夹紧" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\A手动夹紧</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\A手动夹紧</Property>
	</Item>
	<Item Name="A手动移载" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\A手动移载</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\A手动移载</Property>
	</Item>
	<Item Name="A正负压开启" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\A正负压开启</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\A正负压开启</Property>
	</Item>
	<Item Name="B安全门禁用" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\B安全门禁用</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\B安全门禁用</Property>
	</Item>
	<Item Name="B复位" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\B复位</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\B复位</Property>
	</Item>
	<Item Name="B工位NG样件需求" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\B工位NG样件需求</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\B工位NG样件需求</Property>
	</Item>
	<Item Name="B工位OK样件需求" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\B工位OK样件需求</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\B工位OK样件需求</Property>
	</Item>
	<Item Name="B工位校准时间到" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\B工位校准时间到</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\B工位校准时间到</Property>
	</Item>
	<Item Name="B启动信号" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\B启动信号</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\B启动信号</Property>
	</Item>
	<Item Name="B切换为手动" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\B切换为手动</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\B切换为手动</Property>
	</Item>
	<Item Name="B扫码OK" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\B扫码OK</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\B扫码OK</Property>
	</Item>
	<Item Name="B手动封堵" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\B手动封堵</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\B手动封堵</Property>
	</Item>
	<Item Name="B手动盖章" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\B手动盖章</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\B手动盖章</Property>
	</Item>
	<Item Name="B手动夹紧" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\B手动夹紧</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\B手动夹紧</Property>
	</Item>
	<Item Name="B手动移载" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\B手动移载</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\B手动移载</Property>
	</Item>
	<Item Name="B正负压开启" Type="Variable">
		<Property Name="featurePacks" Type="Str">Network</Property>
		<Property Name="Network:AccessType" Type="Str">read/write</Property>
		<Property Name="Network:BuffSize" Type="Str">50</Property>
		<Property Name="Network:ElemSize" Type="Str">1</Property>
		<Property Name="Network:PointsPerWaveform" Type="Str">1</Property>
		<Property Name="Network:ProjectBinding" Type="Str">True</Property>
		<Property Name="Network:ProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\Channel1\Device1\B正负压开启</Property>
		<Property Name="Network:UseBinding" Type="Str">True</Property>
		<Property Name="Network:UseBuffering" Type="Str">True</Property>
		<Property Name="numTypedefs" Type="UInt">0</Property>
		<Property Name="type" Type="Str">Network</Property>
		<Property Name="typeDesc" Type="Bin">&amp;!#!!!!!!!)!"1!&amp;!!!-!%!!!@````]!!!!"!!%!!!!:&amp;1!!!"1!A!!!!!!"!!1!)1!"!!!"!!!!!!!!!!!</Property>
		<Property Name="varSourceProjectPath" Type="Str">我的电脑\OPC.lvlib\OPC1\</Property>
		<Property Name="varSourceProjectSubPath" Type="Str">Channel1\Device1\B正负压开启</Property>
	</Item>
	<Item Name="OPC1" Type="IO Server">
		<Property Name="atrb" Type="Str">0!)!!!Q1!!!,!!!!"B!!!!A!!!"E!'5!91"E!')!91"O!'1!!Q!!!!!!!!!!!!!!"B!!!!M!!!"F!'Y!91"C!'Q!:1"%!'5!9A"V!'=!!A!!!!!'%!!!$1!!!'E!&lt;A"U!'5!=A"G!'%!9Q"F!&amp;1!?1"Q!'5!"B!!!!Q!!!""!(-!?1"O!'-!;!"S!']!&lt;A"P!(5!=Q!'%!!!"Q!!!'Q!&lt;Q"H!%9!;1"M!'5!"B!!!!!!!!!'%!!!"Q!!!'U!91"D!'A!;1"O!'5!"B!!!!E!!!"M!']!9Q"B!'Q!;!"P!(-!&gt;!!'%!!!#Q!!!'U!91"Y!%9!;1"M!'5!5Q"J!(I!:1!$!!9!!!!!!!!!R%!'%!!!"A!!!&amp;!!=A"P!'=!31"%!!91!!!E!!!!4A"B!(1!;1"P!'Y!91"M!#!!31"O!(-!&gt;!"S!(5!&lt;1"F!'Y!&gt;!"T!#Y!4A"*!%]!5!"$!&amp;-!:1"S!(9!:1"S!(-!,A"7!$5!"B!!!"%!!!"S!'5!9Q"P!'Y!&lt;A"F!'-!&gt;!"1!']!&lt;!"M!&amp;)!91"U!'5!!Q!!!!!!!!!!!&amp;Z!"B!!!")!!!"T!'5!=A"W!'5!=A"*!'Y!=Q"U!'%!&lt;A"D!'5!6!"Z!(!!:1!'%!!!#Q!!!%]!&gt;1"U!#!!&lt;Q"G!#!!5!"S!']!9Q!'%!!!#A!!!(5!=!"E!'%!&gt;!"F!&amp;)!91"U!'5!!Q!!!!!!!!!!!#2!"B!!!!U!!!"V!(-!:1"5!'%!:Q"H!'5!=A"5!'E!&lt;1"F!!)!!!!!</Property>
		<Property Name="className" Type="Str">OPC</Property>
	</Item>
</Library>
